### ISSUE TITLE
Design Sprint - Prototype

### ISSUE THREAD

**Issue by LucasSpinosa** [UnBArqDsw2024-2/2024.2_G2_Brecho_Entrega_01#32]
### Summary

Realizar a etapa de Prototype da Design Sprint

### Motivation

Realizar parte da entrega 1 de Arquitetura.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guinuto** [comment]
https://github.com/UnBArqDsw2024-2/2024.2_G2_Brecho_Entrega_01/pull/37
